#!/bin/bash

# Variables
MOUNT_POINT="/opt"

# Install required packages
#yum update -y
yum install -y rsync

# Detect the root device to avoid it
NEW_DISK=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep 'disk' | grep -v 'MOUNTPOINT' | tail -n 1 | awk '{print "/dev/" $1}')

# Check if the disk is found
if [ -z "$NEW_DISK" ]; then
    echo "No unmounted disk found."
    exit 1
fi

echo "Newly attached disk: $NEW_DISK"

# Format the unformatted EBS volume as ext4
echo "Formatting the volume: $EBS_VOLUME_DEVICE"
mkfs.ext4 $NEW_DISK

# Mount the new EBS volume to temporary mount point
mkdir /mnt/temp_opt
mount $NEW_DISK /mnt/temp_opt

# Copy the content of /opt to new temp_opt
rsync -avx /opt/ /mnt/temp_opt/

# unmount temporary /opt
umount /mnt/temp_opt

# Mount point for /opt
mount $NEW_DISK $MOUNT_POINT

# Mount the unformatted EBS volume to /opt temporarily
mount $NEW_DISK $MOUNT_POINT

# Copy the data from /opt to the new EBS volume
#echo "Copying /opt data to $MOUNT_POINT"
#rsync -avx /opt/ $MOUNT_POINT/

# Modify fstab to mount the EBS volume at boot
echo "Updating /etc/fstab"
echo "$NEW_DISK $MOUNT_POINT ext4 defaults,nofail 0 2" >> /etc/fstab

# Ensure the volume mounts automatically after reboot
mount -a
systemctl daemon reload

# Remove the old /opt content (optional, based on the user's preference)
#rm -rf /opt/*
